### ISSUE TITLE
"linting" fix changed API

### ISSUE THREAD

**Issue by biot** [JamesClonk/vultr#29]
Hi,

Commit 3e1b8253ee8b0799febeb79772db9cc8adda6d71 "fix all linting" actually changed the API. This, for example:

https://github.com/JamesClonk/vultr/commit/3e1b8253ee8b0799febeb79772db9cc8adda6d71#diff-3676638119a5a17122a453849c43b293L61

changes the function "CreateDnsRecord" to "CreateDNSRecord". That of course breaks API, and anything that uses it. Case in point, it broke lego (https://github.com/xenolf/lego).

Was this intentional?

**Comment by JamesClonk** [comment]
Hi @biot,
Yes, unfortunately it was an intentional change to satisfy golint. (Ip -> IP, Dns -> DNS, etc..)
I'd hoped anyone using the library to use some form of vendoring/dependency management, but it seems that is not the case with lego. The last tagged version with the old function names is v1.12.0.

I'll open up a PR for lego to fix the code there.

Sorry for the inconvenience.  :cold_sweat:
I hope problems like these get solved soon once Golang gets official dependency management tooling.

**Comment by biot** [comment]
Your PR was merged and all is well again. Thanks for the prompt reaction, keep up the good work!
